security:

  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\Utilisateur
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false


    main:
      lazy: true
      provider: app_user_provider
      logout:
        path: app_logout
        target: app_login
      form_login:
        login_path: app_login
        check_path: app_login
      remember_me:
        secret:   '%kernel.secret%'
        lifetime: 604800  # 1 week in seconds
        path:     /

  access_control:
    -  { path: ^/admin, roles: ROLE_SUPER_ADMIN }
   # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
  # - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED }

framework:
  csrf_protection: true


